eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8081
spring:
  application:
    name: portal
#    服务提供者 向Server发起注册请求 ，另外还有一个服务消费者，就是相当于这个消费者会请求服务提供者
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    cache: false
